version: '3.8'

services:
  transaction-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: mongodb://mongo:27017/exchange_rates
      DB_USERNAME: user
      DB_PASSWORD: password
      MONGO_URL: mongodb://mongo:27017/exchange_rates
      API_KEY: your-twelvedata-api-key
      ADDRESS: http://localhost:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
